### PR TITLE
Building ships

### PR DESCRIPTION
**Pull request by duploli**
Still in progress, but it was my "must have" functionality:

- Can see ship storage:  can be improved by creating 5 datagridview (1 per stockage node)
- For Construction Vessel:
    - Can see if ressources are requested for waiting build order;
    - Can fill requested ressources with one button.
- Various bug fix/code update requested for previous feature.

For information:
 - Works with X rebirth V4.1 and add-ons
 - Need Factions standing branch

### CODE REVIEW

**Comment by nemesis1782** [comment]
Hi Duploli,

sorry for my absence, you've been doing some great work! Nice to see that the editor hasn't died in my absence.

Have you release any of this on the egosoft forum?

Greetz,

Nemesis

**Comment by duploli** [comment]
I didn't put anything on the forum:
- I don't know how the "Click-Once applications" works and how you pull updates to users.
- I'm afraid to kill people saves :-p

**Comment by nemesis1782** [comment]
Hehe, I understand. No worries. ClickOnce Functionality is currently dead since the server it was hosted on is no longer up :)

I suggest we start with a zip release. Is this branch stable and ready to be pulled?

We'll get into the click once at a later time. I created a project with things I would like to get in order. I'll use the wiki to start creating some documentation. But before I do anything I need to get my dev env up and running :P

**Comment by nemesis1782** [comment]
Also about peoples saves. I make it a point to anywhere that even though the app makes a backup of them. They are responsible to make a backup themselves and not loose any game saves. We can always make a mistake ;)

**Pull request merged**
