### PR TITLE
Factions standing

### PR DESCRIPTION
**Pull request by duploli**
Editing standing between player and faction, and between two factions is now working.
About issue #2, the only change I did not implement is to select the player faction by default.
I did not check the faction licences capacity.

Could you have a look on the change I did on the GUI (first time ever I use VS designer) to be sure I did not make mistake/error on this part?

### CODE REVIEW

**Comment by nemesis1782** [comment]
Hi,


will check it in the weekend and report back.


Greetz,


Davy

________________________________

**Comment by duploli** [comment]
Also solving issue #4.

**Comment by duploli** [comment]
More stuff in this branch:
- Fixing some NullReferenceException (causing a lot of text in the logger)
- Translation update: some "text" are composed with multiple group of {#####,#####}
- In/For the universe editor: 
    - fixing minor bug preventing ships selection
    - adding support for deployed building ships

**Comment by nemesis1782** [comment]
Is this branch stable as well? If so you may merge the pull requests yourself (not sure if you have the permissions and do not know how to give them to you)

**Pull request merged**
